# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF46CdfQVnFjF361Wbdm59xOYFyPFSGt
"""

!pip install streamlit fredapi scikit-learn openai plotly
import streamlit as st
import pandas as pd
import numpy as np
from fredapi import Fred
from sklearn.linear_model import LinearRegression
from openai import OpenAI
import plotly.express as px

# 1. SIDEBAR: Secure API Key Inputs
with st.sidebar:
    st.title("🔑 Startup Credentials")
    fred_key = st.text_input("6b840502e191e6de512861ee27f2ac9d", type="password")
    ai_key = st.text_input("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", type="password")
    st.info("These keys allow your AI to fetch live govt data and 'think'.")

st.title("📈 TCPI: Teen Consumer Price Index")
st.markdown("### *AI-Powered Economic Forecasting for the Next Generation*")

if fred_key and ai_key:
    # 2. DATA ENGINE: Fetch Live Inflation Data
    fred = Fred(api_key=fred_key)
    raw_data = fred.get_series('CPIAUCSL').dropna().tail(12)

    df = pd.DataFrame(raw_data, columns=['Price_Index'])
    df['Month_Index'] = np.arange(len(df))

    # 3. AI ENGINE: Linear Regression Prediction
    X = df[['Month_Index']].values
    y = df['Price_Index'].values
    model = LinearRegression().fit(X, y)

    next_month = np.array([[len(y)]])
    prediction = model.predict(next_month)[0]

    # 4. DASHBOARD: Show the Stats
    col1, col2 = st.columns(2)
    col1.metric("Current Index", f"{y[-1]:.2f}")
    col2.metric("AI Forecast", f"{prediction:.2f}", f"{prediction - y[-1]:.2f}")

    # Visual Chart
    fig = px.line(df, x='Month_Index', y='Price_Index', title="Inflation Trend (Last 12 Months)")
    fig.add_scatter(x=[len(y)], y=[prediction], mode='markers', name='AI Prediction', marker=dict(size=12, color='red'))
    st.plotly_chart(fig)

    # 5. CHATBOT: The "Voice" of your Startup
    st.divider()
    st.subheader("💬 Ask the Econ-Bot")

    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("Ex: Why is the AI predicting a price hike?"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # AI Response Logic
        client = OpenAI(base_url="https://api.groq.com", api_key=ai_key)
        context = f"Live Data: Current CPI {y[-1]:.2f}, AI Forecast {prediction:.2f}."

        response = client.chat.completions.create(
            model="llama3-8b-8192",
            messages=[
                {"role": "system", "content": f"You are a Finance Expert for 8th graders. Use this context: {context}"},
                {"role": "user", "content": prompt}
            ]
        )

        full_response = response.choices[0].message.content
        with st.chat_message("assistant"):
            st.markdown(full_response)
        st.session_state.messages.append({"role": "assistant", "content": full_response})

else:
    st.warning("Please enter your API keys in the sidebar to launch the Startup Engine.")